databases:
  - name: budgetti_database
    databaseName: budgetti_database
    user: budgetti_user
    plan: free

services:
  - type: web
    name: budget_app
    runtime: ruby
    plan: free
    buildCommand: "bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean;"
    # preDeployCommand: "./bin/rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budgetti_database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default